import { env } from '@/env';

// SHARED
export const UPSTASH_PROJECT_URL = env.NEXT_PUBLIC_UPSTASH_PROJECT_URL;
export const SUPABASE_PROJECT_URL = env.NEXT_PUBLIC_SUPABASE_PROJECT_URL;

// iOS
export const APP_STORE_CONNECT_URL = env.NEXT_PUBLIC_APP_STORE_CONNECT_URL;
export const IOS_GITHUB_URL = env.NEXT_PUBLIC_IOS_GITHUB_URL;

// WEB
export const WEB_VERCEL_PROJECT_URL = env.NEXT_PUBLIC_WEB_VERCEL_PROJECT_URL;
export const WEB_GITHUB_URL = env.NEXT_PUBLIC_WEB_GITHUB_URL;
export const WEB_URL = env.NEXT_PUBLIC_WEB_URL;

// ADMIN
export const ADMIN_VERCEL_PROJECT_URL =
  env.NEXT_PUBLIC_ADMIN_VERCEL_PROJECT_URL;
export const ADMIN_APP_GITHUB_URL = env.NEXT_PUBLIC_ADMIN_APP_GITHUB_URL;
export const ADMIN_URL = env.NEXT_PUBLIC_ADMIN_URL;
